version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.16
executors:
  build:
    docker:
      - image: cimg/base:2023.04

workflows:
  ci-cd:
    jobs:

      - gcp-gcr/build-and-push-image:
          name: Build Image
          executor: build
          context: gcp-oidc-docker-registry
          dockerfile: Dockerfile
          registry-url: eu.gcr.io
          use_oidc: true
          image: certspotter
          tag: ${CIRCLE_SHA1}
          # https://circleci.com/docs/2.0/building-docker-images/#docker-version
          remote-docker-version: default
          setup-remote-docker: true
          use-docker-layer-caching: true
